name: Fetch Keystore
on: workflow_dispatch
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Decode keystore
        run: echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > /tmp/cesia-debug.keystore
      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: cesia-debug-keystore
          path: /tmp/cesia-debug.keystore
          retention-days: 1
